#!/usr/bin/env python

import rospy
from std_srvs.srv import Empty, EmptyResponse
from std_msgs.msg import Float64, Bool

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from iss_docking_automation import StateBuffer

import time
import numpy as np

START_DELAY = 5.0
NUM_MEASUREMENTS = 8
UPDATE_RATE = 10

class Simulator():
    def __init__(self):
        self._driver = webdriver.Firefox()
        self._driver.get('https://iss-sim.spacex.com/')

        WebDriverWait(self._driver, 30) \
            .until(EC.element_to_be_clickable((By.ID, 'begin-button'))).click()

        WebDriverWait(self._driver, 30) \
            .until(EC.visibility_of_element_located((By.ID, 'hud-darken')))

        time.sleep(START_DELAY)

        self._x = self._driver.find_element_by_id('x-range') \
                .find_element_by_class_name('distance')

        self._y = self._driver.find_element_by_id('y-range') \
               .find_element_by_class_name('distance')

        self._z = self._driver.find_element_by_id('z-range') \
                .find_element_by_class_name('distance')

        self._yaw = self._driver.find_element_by_id('yaw') \
                .find_element_by_class_name('error')

        self._pitch = self._driver.find_element_by_id('pitch') \
                .find_element_by_class_name('error')

        self._roll = self._driver.find_element_by_id('roll') \
                .find_element_by_class_name('error')

        self._translation_status = self._driver \
                .find_element_by_id('precision-translation-status')

        self._rotation_status = self._driver \
                .find_element_by_id('precision-rotation-status')

        self._toggle_translation_precise = self._driver \
                .find_element_by_id('toggle-translation')

        self._toggle_rotation_precise = self._driver \
                .find_element_by_id('toggle-rotation')

    def __del__(self):
        self._driver.close()

    ###########################################################################
    # Translations
    ###########################################################################

    def translate_left(self):
        ActionChains(self._driver).send_keys('a').perform()

    def translate_right(self):
        ActionChains(self._driver).send_keys('d').perform()

    def translate_up(self):
        ActionChains(self._driver).send_keys('w').perform()

    def translate_down(self):
        ActionChains(self._driver).send_keys('s').perform()

    def translate_forward(self):
        ActionChains(self._driver).send_keys('e').perform()

    def translate_backward(self):
        ActionChains(self._driver).send_keys('q').perform()

    ###########################################################################
    # Rotations
    ###########################################################################

    def yaw_left(self):
        ActionChains(self._driver).send_keys(Keys.LEFT).perform()

    def yaw_right(self):
        ActionChains(self._driver).send_keys(Keys.RIGHT).perform()

    def pitch_up(self):
        ActionChains(self._driver).send_keys(Keys.UP).perform()

    def pitch_down(self):
        ActionChains(self._driver).send_keys(Keys.DOWN).perform()

    def roll_left(self):
        ActionChains(self._driver).send_keys('<').perform()

    def roll_right(self):
        ActionChains(self._driver).send_keys('>').perform()

    ###########################################################################
    # Measurements
    ###########################################################################

    def get_x(self):
        return float(self._x.text[:-2])

    def get_y(self):
        return float(self._y.text[:-2])

    def get_z(self):
        return float(self._z.text[:-2])

    def get_yaw(self):
        return float(self._yaw.text[:-1])

    def get_pitch(self):
        return float(self._pitch.text[:-1])

    def get_roll(self):
        return float(self._roll.text[:-1])

    ###########################################################################
    # Precision
    ###########################################################################

    def is_translation_precise(self):
        return 'large' not in self._translation_status.get_attribute('class')

    def toggle_translation_precise(self, _):
        self._toggle_translation_precise.click()
        return EmptyResponse()

    def is_rotation_precise(self):
        return 'large' not in self._rotation_status.get_attribute('class')

    def toggle_rotation_precise(self, _):
        self._toggle_rotation_precise.click()
        return EmptyResponse()

class ActionRateHolder:
    def __init__(self):
        self._rates = {}

    def handle_translate_left(self, msg):
        self._rates['translate_left'] = msg.data

    def handle_translate_right(self, msg):
        self._rates['translate_right'] = msg.data

    def handle_translate_up(self, msg):
        self._rates['translate_up'] = msg.data

    def handle_translate_down(self, msg):
        self._rates['translate_down'] = msg.data

    def handle_translate_forward(self, msg):
        self._rates['translate_forward'] = msg.data

    def handle_translate_backward(self, msg):
        self._rates['translate_backward'] = msg.data

    def is_initialized(self):
        return len(self._rates) == 6

    def get_rates(self):
        return self._rates

def transmit_measurements(step, simulator,
                          x_pub, y_pub, zpub,
                          yaw_pub, pitch_pub, roll_pub):

    if step % NUM_MEASUREMENTS == 0:
        x_pub.publish(simulator.get_x())

    if step % NUM_MEASUREMENTS == 1:
        y_pub.publish(simulator.get_y())

    if step % NUM_MEASUREMENTS == 2:
        z_pub.publish(simulator.get_z())

    if step % NUM_MEASUREMENTS == 3:
        yaw_pub.publish(simulator.get_yaw())

    if step % NUM_MEASUREMENTS == 4:
        pitch_pub.publish(simulator.get_pitch())

    if step % NUM_MEASUREMENTS == 5:
        roll_pub.publish(simulator.get_roll())

    if step % NUM_MEASUREMENTS == 6:
        translation_precise_pub.publish(simulator.is_translation_precise())

    if step % NUM_MEASUREMENTS == 7:
        rotation_precise_pub.publish(simulator.is_rotation_precise())

def apply_controls(simulator, control_rates):

    # Apply translations
    if np.random.random() < -control_rates['x']:
        simulator.translate_forward()
    if np.random.random() <  control_rates['x']:
        simulator.translate_backward()
    if np.random.random() < -control_rates['y']:
        simulator.translate_left()
    if np.random.random() <  control_rates['y']:
        simulator.translate_right()
    if np.random.random() < -control_rates['z']:
        simulator.translate_down()
    if np.random.random() < control_rates['z']:
        simulator.translate_up()

    # Apply rotations
    if np.random.random() < -control_rates['yaw']:
        simulator.yaw_right()
    if np.random.random() <  control_rates['yaw']:
        simulator.yaw_left()
    if np.random.random() < -control_rates['pitch']:
        simulator.pitch_down()
    if np.random.random() <  control_rates['pitch']:
        simulator.pitch_up()
    if np.random.random() < -control_rates['roll']:
        simulator.roll_right()
    if np.random.random() < control_rates['roll']:
        simulator.roll_left()

if __name__ == '__main__':
    rospy.init_node('iss_simulator')
    simulator = Simulator()
    controls = StateBuffer()

    # Translation controls
    rospy.Subscriber('controls/x', Float64, controls.handle_x)
    rospy.Subscriber('controls/y', Float64, controls.handle_y)
    rospy.Subscriber('controls/z', Float64, controls.handle_z)

    # Rotation controls
    rospy.Subscriber('controls/yaw'  , Float64, controls.handle_yaw)
    rospy.Subscriber('controls/pitch', Float64, controls.handle_pitch)
    rospy.Subscriber('controls/roll' , Float64, controls.handle_roll)

    # Measurement publishers
    x_pub     = rospy.Publisher('measurements/x'    , Float64, queue_size=1)
    y_pub     = rospy.Publisher('measurements/y'    , Float64, queue_size=1)
    z_pub     = rospy.Publisher('measurements/z'    , Float64, queue_size=1)
    yaw_pub   = rospy.Publisher('measurements/yaw'  , Float64, queue_size=1)
    pitch_pub = rospy.Publisher('measurements/pitch', Float64, queue_size=1)
    roll_pub  = rospy.Publisher('measurements/roll' , Float64, queue_size=1)

    translation_precise_pub = rospy.Publisher('controls/translation_precise',
                                              Bool, queue_size=1)

    rotation_precise_pub = rospy.Publisher('controls/rotation_precise',
                                           Bool, queue_size=1)

    rospy.Service('controls/toggle_translation_precise', Empty,
                  simulator.toggle_translation_precise)

    rospy.Service('controls/toggle_rotation_precise', Empty,
                  simulator.toggle_rotation_precise)

    rate = rospy.Rate(UPDATE_RATE)
    step = 0
    while not rospy.is_shutdown():

        try:
            transmit_measurements(step, simulator,
                                  x_pub, y_pub, z_pub,
                                  yaw_pub, pitch_pub, roll_pub)

            if controls.is_initialized():
                apply_controls(simulator, controls.get_state())

        # Ugly hack to prevent the node from crashing when game ends
        except: pass


        step += 1
        rate.sleep()
